subtype added for biometric capture
mosip/idp-ui pull request #13
Opened 2022-11-02 13:27 UTC by anshulv1401

1. subtype configuration added for biometric capture request.
2. i18n support added for claims.
3. if idpApiUrl starts with "/" then baseUrl will be the concatenation of origin-domain and idpApiUrl.
4. transactionId for bio captured reverted to idp transactionId.
5. relative api-url added in the configuration file.

2022-11-07 06:54 UTC, gsasikumar requested changes

2022-11-07 06:54 UTC, gsasikumar commented on src/components/IdpDetails.js
> +      { icon: null, name: "internal_api", value: "https://api.dev.mosip.net" },
Why is this hard coded?

2022-11-07 06:54 UTC, gsasikumar commented on src/constants/clientConstants.js
> +const supportedLanguages = {
this should be configurable

2022-11-07 06:54 UTC, gsasikumar commented on src/i18n.js
>  import translationEN from "./locales/en.json";
All these files should be dynamically picked.

2022-11-07 06:54 UTC, gsasikumar commented on src/i18n.js
> +  hi: {
whats this? configuration per language?

2022-11-07 06:54 UTC, gsasikumar commented on src/locales/en.json
> +    "consent_request_rejected": "Consent Request Rejected!",
All the locales have to come from artifactory url. Can you speak to mayura or aravindan once to understand how they are getting this file?

2022-11-07 12:02 UTC, anshulv1401 commented on public/env_configs.js
> +  idpApiUrl: "http://localhost:8088/v1/idp",
idpApiUrl removed from all places. Relative URL "/v1/idp" added in env file, which will be constant.

2022-11-07 12:04 UTC, anshulv1401 commented on src/constants/clientConstants.js
> +const supportedLanguages = {
these are configuration keys, values for which will be sent from the IDP OAuth-details endpoint.

2022-11-09 07:02 UTC, anshulv1401 commented on src/i18n.js
>  import translationEN from "./locales/en.json";
Raised a ticked to dynamically load i18n file
[MOSIP-24665](https://mosip.atlassian.net/browse/MOSIP-24665)

2022-11-09 07:06 UTC, anshulv1401 commented on src/locales/en.json
> +    "consent_request_rejected": "Consent Request Rejected!",
Raised a ticked to download i18n bundle from artifactory and host from idp-ui nginx
[MOSIP-24666](https://mosip.atlassian.net/browse/MOSIP-24666)

2022-11-09 13:59 UTC, anshulv1401 commented on src/i18n.js
> +  hi: {
removed

2022-11-09 13:59 UTC, anshulv1401 commented on src/i18n.js
>  import translationEN from "./locales/en.json";
issue fixed

2022-11-16 07:08 UTC, gsasikumar requested changes

2022-11-16 10:05 UTC, anshulv1401 commented on README.md
> +* /Authorize:
changed it to /authorize

2022-11-16 10:05 UTC, anshulv1401 commented on README.md
> +* /Login:
changed it to /login

2022-11-16 10:05 UTC, anshulv1401 commented on README.md
> +* /Consent: Consent is a page that prompts the user to provide consent to share one's details from the MOSIP to the relying party. It shows authorize scope that needs to be permitted and essential an
/consent

2022-11-16 10:06 UTC, anshulv1401 commented on README.md
> +    Each component is capable of authorizing the user using its challenge details. These options to sign in will be presented to the user based on the auth factors that get returned from the /Authori
Paragraph modified

2022-11-17 04:57 UTC, ase-101 commented on README.md
> +IDP Services are based on [OpenID specs](https://openid.net/specs/openid-connect-core-1_0.html).
we will take care of this in https://mosip.atlassian.net/browse/MOSIP-24791

2022-11-17 05:27 UTC, gsasikumar approved these changes

2022-11-17 05:27 UTC, merged