MOSIP-25236 adhoc ui changes
mosip/idp-ui pull request #26
Opened 2022-12-14 07:19 UTC by anshulv1401

1. Make const height for all components
2. Changes in Inji comp
 a. Replace login with inji
 b. Remove inji app from QRcode
3. Increase QRcode size
4. implemented fade QRcode for expiry

2022-12-15 12:57 UTC, gsasikumar requested changes

2022-12-15 12:57 UTC, gsasikumar commented on src/components/OtpVerify.js
> +      t("resend_otp_counter", { timeLeft: resendOtpTimeout + "s" })
This is only in seconds? We will need minute:seconds as a running counter

2022-12-16 08:24 UTC, anshulv1401 commented on src/components/OtpVerify.js
> +      t("resend_otp_counter", { timeLeft: resendOtpTimeout + "s" })
resolved

2022-12-16 10:16 UTC, gsasikumar approved these changes

2022-12-16 10:16 UTC, merged