Develop
mosip/idp-ui pull request #35
Opened 2023-01-13 13:08 UTC by anshulv1401

[MOSIP-25505](https://mosip.atlassian.net/browse/MOSIP-25505) RTL support added
[MOSIP-25770](https://mosip.atlassian.net/browse/MOSIP-25770) info icon on the claim added

2023-01-31 08:45 UTC, gsasikumar requested changes

2023-01-31 10:47 UTC, gsasikumar requested changes

2023-01-31 10:47 UTC, gsasikumar commented on .env
> +REACT_APP_SEND_OTP_CAPTCHA_SITE_KEY="6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI"
This is supposed to be secret? do you need a valid one here? or can you have just a dummy value? also revoke this site key.

2023-01-31 10:47 UTC, gsasikumar commented on .env
>  REACT_APP_SBI_PORT_RANGE="4501-4600"
Why are we calling everything as REACT_APP ?? This is eSignet correct?

2023-01-31 10:47 UTC, gsasikumar commented on src/services/authService.js
> +  post_SendOtp = async (transactionId, individualId, otpChannels, captchaToken) => {
What if a captcha is not needed?

2023-01-31 10:47 UTC, gsasikumar commented on .env
> +REACT_APP_SEND_OTP_SHOW_CAPTCHA="false"
why is this "SEND_OTP_SHOW_CAPTCHA"? why can't we just call it as just SHOW_CAPTCHA

2023-01-31 10:47 UTC, gsasikumar commented on package.json
> +    "react-google-recaptcha": "^2.1.0",
This should be added only if needed. Is it possible? if not ok.

2023-01-31 10:58 UTC, anshulv1401 commented on .env
> +REACT_APP_SEND_OTP_CAPTCHA_SITE_KEY="6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI"
"6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI" is a dummy key. It shows like this
![image](https://user-images.githubusercontent.com/31562315/215741822-31882bf9-80aa-4b21-b55d-1ea601c4739e.png)

2023-01-31 11:06 UTC, gsasikumar commented on .env
> +REACT_APP_SEND_OTP_CAPTCHA_SITE_KEY="6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI"
grt

2023-01-31 11:06 UTC, anshulv1401 commented on src/services/authService.js
> +  post_SendOtp = async (transactionId, individualId, otpChannels, captchaToken) => {
then null will be passed, and the request body will not be affected.

2023-01-31 11:08 UTC, anshulv1401 commented on .env
> +REACT_APP_SEND_OTP_SHOW_CAPTCHA="false"
SEND_OTP suggests the component these env variables are used in. can be removed if required.

2023-01-31 11:09 UTC, gsasikumar commented on src/services/authService.js
> +  post_SendOtp = async (transactionId, individualId, otpChannels, captchaToken) => {
ok grt

2023-01-31 11:16 UTC, gsasikumar approved these changes

2023-01-31 11:16 UTC, merged

2023-02-01 05:51 UTC, anshulv1401 commented on public/locales/en.json
> +    "idp_details_heading": "OIDC Details",
IDP Details will updated as  Esignet well-known APIs

2023-02-01 05:51 UTC, anshulv1401 commented on public/locales/en.json
> +    "login_paragraph": "Have not registered for e-Signet yet?",
login_paragraph is not used in the code, hence removed

2023-02-01 05:51 UTC, anshulv1401 commented on src/components/L1Biometrics.js
> +        oAuthDetailsService.getTransactionId(),
renamed oAuthDetailsService as openIDConnectService

2023-02-01 07:35 UTC, anshulv1401 commented on src/components/OtpVerify.js
> +        let responseB64 = oAuthDetailsService.encodeBase64(oAuthDetailsService.getOuthDetails());
name corrected to getOAuthDetails()

2023-02-01 07:35 UTC, anshulv1401 commented on src/pages/Login.js
>  import IDPQRCode from "../components/IDPQRCode";
IDPQRCode name updated to LoginQRCode

2023-02-01 07:37 UTC, anshulv1401 commented on .env
> +REACT_APP_SEND_OTP_SHOW_CAPTCHA="false"
SEND_OTP_SHOW_CAPTCHA renamed to REACT_APP_CAPTCHA_ENABLE which will be a comma-separated list of components where the captcha needs to be shown

2023-02-01 07:38 UTC, anshulv1401 commented on package.json
> +    "react-google-recaptcha": "^2.1.0",
we are dependent on the OAuth response to know if we want to show a captcha or not. Hence cannot determine the library's requirement at the build time.