Parsing and forwarding claims from request to IDP
mosip/idp-ui pull request #4
Opened 2022-09-07 04:32 UTC by anshulv1401

2022-10-11 09:00 UTC, gsasikumar commented
Can we remove all the utils related images?

2022-10-11 12:40 UTC, anshulv1401 commented
> Can we remove all the utils related images?

2022-10-11 12:43 UTC, anshulv1401 commented
> > Can we remove all the utils related images?

All utils related images removed

2022-10-12 17:49 UTC, gsasikumar requested changes
Some comments are generic. Can you follow that pattern

2022-10-12 17:49 UTC, gsasikumar commented on src/components/L1Biometrics.js
> +import { encodeBase64 } from "../services/cryptoService";
The ideal way is to inject and not import the services

2022-10-12 17:49 UTC, gsasikumar commented on src/components/L1Biometrics.js
> +import { post_AuthenticateUser } from "../services/AuthService";
We should not be importing rather we should be injecting the service or handles.

2022-10-12 17:49 UTC, gsasikumar commented on src/components/L1IndividualBiometric.js
> +import { post_AuthenticateUser } from "../services/AuthService";
same comment. isolate service and components.

2022-10-13 15:02 UTC, anshulv1401 commented on .env
> +REACT_APP_SBI_PURPOSE=Auth
Done

2022-10-13 15:04 UTC, anshulv1401 commented on .env
> +REACT_APP_SBI_TIMEOUT=30
Unit for timeout is second. updated the Key to REACT_APP_SBI_TIMEOUT_IN_SECONDS

2022-10-13 15:05 UTC, anshulv1401 commented on .env.development
> +REACT_APP_IDP_BASE_URL=http://localhost:8088/v1/idp
key REACT_APP_IDP_BASE_URL update to REACT_APP_IDP_API_URL

2022-10-13 15:09 UTC, anshulv1401 commented on nginx/nginx.conf
> +    index  index.html index.htm;
htm is an old extention of html.

2022-10-13 15:11 UTC, anshulv1401 commented on src/components/Consent.js
> +import { otpFields } from "../constants/formFields";
Removed

2022-10-13 15:11 UTC, anshulv1401 commented on src/components/Consent.js
> +fields.forEach((field) => (fieldsState["Otp" + field.id] = ""));
Removed

2022-10-14 12:46 UTC, anshulv1401 commented on src/components/Consent.js
> +import { post_AuthCode } from "../services/AuthService";
isolated services and components

2022-10-14 12:47 UTC, anshulv1401 commented on src/components/L1Biometrics.js
> +import { post_AuthenticateUser } from "../services/AuthService";
isolated services and components

2022-10-14 12:47 UTC, anshulv1401 commented on src/components/L1IndividualBiometric.js
> +import { post_AuthenticateUser } from "../services/AuthService";
isolated services and components

2022-10-27 12:31 UTC, gsasikumar approved these changes

2022-10-27 12:34 UTC, gsasikumar approved these changes

2022-10-27 12:34 UTC, merged